/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 level3.gltf --transform
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/glb/level3-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (props.play) {
      actions["Key.002Action"].play();
    }
  }, [props.play]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="result_003">
          <mesh
            name="result-5_015"
            geometry={nodes["result-5_015"].geometry}
            material={materials["leaf_disease.001"]}
            morphTargetDictionary={nodes["result-5_015"].morphTargetDictionary}
            morphTargetInfluences={nodes["result-5_015"].morphTargetInfluences}
          />
          <mesh
            name="result-5_015_1"
            geometry={nodes["result-5_015_1"].geometry}
            material={materials["leaf_disease.001"]}
            morphTargetDictionary={
              nodes["result-5_015_1"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_015_1"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_015_2"
            geometry={nodes["result-5_015_2"].geometry}
            material={materials["leaf_disease.001"]}
            morphTargetDictionary={
              nodes["result-5_015_2"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_015_2"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_015_3"
            geometry={nodes["result-5_015_3"].geometry}
            material={materials["leaf_disease.001"]}
            morphTargetDictionary={
              nodes["result-5_015_3"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_015_3"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_015_4"
            geometry={nodes["result-5_015_4"].geometry}
            material={materials["petals.001"]}
            morphTargetDictionary={
              nodes["result-5_015_4"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_015_4"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_015_5"
            geometry={nodes["result-5_015_5"].geometry}
            material={materials["stem.001"]}
            morphTargetDictionary={
              nodes["result-5_015_5"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_015_5"].morphTargetInfluences
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/level3-transformed.glb");
