/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 bellpepper_step3.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/glb/bellpepper_step3-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, 20]}
        rotation={[Math.PI, -1.21, Math.PI]}
        scale={20}
      >
        <mesh geometry={nodes["result-2"].geometry} material={materials.stem} />
        <mesh
          geometry={nodes["result-2_1"].geometry}
          material={materials.leaf_disease}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/bellpepper_step3-transformed.glb");
