/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 bg5.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/glb/bg5-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SCALE5.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload("/glb/bg5-transformed.glb");
