/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 new-oneside.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/glb/new-oneside-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["oneside-bg-5"].geometry}
        material={materials["Material.002"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/glb/new-oneside-transformed.glb");
