/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 newbg-test.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/glb/newbg-test-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="new-bg-test"
          geometry={nodes["new-bg-test"].geometry}
          material={materials.Material}
          scale={20}
        />
        <group name="result_030">
          <mesh
            name="result-5_013"
            geometry={nodes["result-5_013"].geometry}
            material={materials["stem.002"]}
            morphTargetDictionary={nodes["result-5_013"].morphTargetDictionary}
            morphTargetInfluences={nodes["result-5_013"].morphTargetInfluences}
          />
          <mesh
            name="result-5_013_1"
            geometry={nodes["result-5_013_1"].geometry}
            material={materials["fruit-ripe"]}
            morphTargetDictionary={
              nodes["result-5_013_1"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_1"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_2"
            geometry={nodes["result-5_013_2"].geometry}
            material={materials["leaf_disease.002"]}
            morphTargetDictionary={
              nodes["result-5_013_2"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_2"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_3"
            geometry={nodes["result-5_013_3"].geometry}
            material={materials["leaf_disease.002"]}
            morphTargetDictionary={
              nodes["result-5_013_3"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_3"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_4"
            geometry={nodes["result-5_013_4"].geometry}
            material={materials["leaf_disease.002"]}
            morphTargetDictionary={
              nodes["result-5_013_4"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_4"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_5"
            geometry={nodes["result-5_013_5"].geometry}
            material={materials["leaf_disease.002"]}
            morphTargetDictionary={
              nodes["result-5_013_5"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_5"].morphTargetInfluences
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/newbg-test-transformed.glb");
